# 第12章 通过异常处理错误

## 1.概述

使用异常所带来的一个明显的好处是，降低错误处理代码的复杂度。完成任务的代码没有与错误检查的代码混在一起。

hrowable 可以用来表示任何可以作为异常抛出的类，分为两种： **Error** 和 **Exception**。其中 Error 用来表示 JVM 无法处理的错误，Exception 分为两种：

- **受检异常** ：需要用 try...catch... 语句捕获并进行处理，并且可以从异常中恢复；
- **非受检异常** ：(RuntimeException)是程序运行时错误，例如除 0 会引发 Arithmetic Exception，此时程序崩溃并且无法恢复。

![Snipaste_2019-08-14_14-16-10.jpg](https://i.loli.net/2019/08/14/KM5YJE9R48VHAjU.jpg)
## 2.基本异常

异常情形：是指阻止当前方法或作用域继续执行的问题。

异常也是用new在堆上创建异常对象，因此也伴随着空间的分配和构造器的调用。所有的异常都有两个构造器：一个是默认构造器；另一个是接受接受字符作为参数，以便把相关的信息放入异常对象的构造器。

## 3.捕获异常

**监控区域**：是一段可能产生异常的代码，并且后面跟着处理这些异常的代码。

异常处理程序：处理异常的程序。

```java
try{
    
} catch(Type1 id1){
    
}catch(Type2 id2){
    
}catch(Type3 id3){
    
}
```

异常处理程序必须紧跟在try块之后。当异常被抛出时，异常处理处理机制将负责搜寻参数与异常类型相匹配的第一个处理程序。然后进入catch字句执行，此时认为异常得到了处理。

异常处理理论上的两个基本模型：**终止模型、恢复模型**

## 4.创建自定义异常

在异常处理程序中，调用Throwable类(Exception即从此类继承)中声明的printStackTrace()方法，可以将信息输出到标准错误流。

异常与记录日志：

```java
import java.util.logging.*;
import java.io.*;

public class LoggingExceptions2 {
	private static Logger logger = Logger.getLogger("LoggingExceptions2");

	static void logException(Exception e) {
		StringWriter trace = new StringWriter();
		e.printStackTrace(new PrintWriter(trace));
		logger.severe(trace.toString());
	}

	public static void main(String[] args) {
		try {
			throw new NullPointerException();
		} catch (NullPointerException e) {
			logException(e);
		}
	}
}/* Output: (90% match)
Aug 30, 2005 4:07:54 PM LoggingExceptions2 logException
SEVERE: java.lang.NullPointerException
        at LoggingExceptions2.main(LoggingExceptions2.java:16)
*///:~

```

## 5.异常说明

异常声明：属于方法声明的一部分，紧跟在在形式参数列表之后。

## 6.捕获所有异常

可以通过Exception来捕获所有的异常，因此它一般方法处理程序列表的末尾，以防止抢在其他处理程序之前先把异常捕获了。因为Exception是与编程有关的所有异常类的基类。

在所有异常的基类Throwable中有方法：

* `String getMessage()`:获取异常详细信息
* `void printStackTrace()`:打印Throwable和Throwable的调用栈轨迹。调用栈显示了“把你带到异常抛出地点”的方法调用序列。

```java
public class ExceptionMethods {
  public static void main(String[] args) {
    try {
      throw new Exception("My Exception");
    } catch(Exception e) {
      print("Caught Exception");
      print("getMessage():" + e.getMessage());
      print("getLocalizedMessage():" +
        e.getLocalizedMessage());
      print("toString():" + e);
      print("printStackTrace():");
      e.printStackTrace(System.out);
    }
  }
} /* Output:
Caught Exception
getMessage():My Exception
getLocalizedMessage():My Exception
toString():java.lang.Exception: My Exception
printStackTrace():
java.lang.Exception: My Exception
        at ExceptionMethods.main(ExceptionMethods.java:8)
*///:~
```

**栈轨迹**
printStackTrace()方法所提供的信息可以通过getStackTrace()方法直接方法，这个方法将返回一个由轨迹中的元素所构成的数组，其中每一个元素都表示栈中的一帧。元素0是栈顶元素，并且是调用序列中最后一个方法调用(这个Throwable被创建和抛出之处)。

```java
//: exceptions/WhoCalled.java
// Programmatic access to stack trace information.

public class WhoCalled {
  static void f() {
    // Generate an exception to fill in the stack trace
    try {
      throw new Exception();
    } catch (Exception e) {
      for(StackTraceElement ste : e.getStackTrace())
        System.out.println(ste.getMethodName());// 直接打印ste可以显示详细信息
    }
  }
  static void g() { f(); }
  static void h() { g(); }
  public static void main(String[] args) {
    f();
    System.out.println("--------------------------------");
    g();
    System.out.println("--------------------------------");
    h();
  }
} /* Output:
f
main
--------------------------------
f
g
main
--------------------------------
f
g
h
main
*///:~
```

**重新抛出异常**

当捕获异常后，我们可以再把捕获的**异常引用**抛出，交给上一级环境中的异常处理程序，同一个try块中的后续catch字句会被忽略。此外，异常对象的所有信息都得以保持，所以高一级环境中捕获此异常的处理程序可以从这个异常对象中得到所有信息。

如果只是把当前异常对象重新抛出，那么printStackTrace()方法显示的将是原来异常抛出点的调用栈信息，而非重新抛出的信息。可以调用fillInStackTrace()方法，这将返回一个Throwable对象，它是通过把**当前调用栈**的信息填入原来那个异常对象而建立的，而之前的栈信息将丢失，异常发生点改变。即：当再高一级的异常处理程序得到这个异常时，异常发生点变为调用printStackTrace()方法。

### 异常链

异常链：捕获一个异常后抛出另一个异常，并且把原始异常的信息保存下来。

Throwable的子类在构造器中都可以接受一个cause（因由）对象作为参数。这个cause就用来表示原始异常，这样吧原始异常传递给新异常，使得即使在当前位置创建并抛出了新的异常，也能通过这个异常链追踪到异常最初的发生位置。

## 7.Java标准异常

异常的基本概念：用名称代表发生的问题，并且异常的名称应该可以望文知意。

注意：只能在代码中忽略RuntimeException（及其子类）类型的异常，其他类型异常的处理都是由编译器强制实施的。究其原因，RuntimeException代表的是编程错误：即

* 无法预料的错误。比如从你控制范围之外传递进来的null引用。
* 作为程序员，应该在代码中进行检查的错误。在一个地方发生的异常，常常会在另一个地方导致错误。

不应该把Java异常处理机制当成单一用途的工具。它被设计用来处理一些运行时错误，这些错误往往是由代码控制能力之外的因素导致的；并且，他对于发现某些编译器无法检测到的编程错误，也是非常重要的。

## 8.使用finally进行清理

finally字句中的代码，无论try 块中的异常是否会抛出，它都会得到执行。

另外当try块中有return时，finally依然会执行。

但try语句中有System.exit(0);语句时，将不会执行，因为该语句代表停止JVM。

异常的丢失

```JAVA
public class ExceptionSilencer {
  public static void main(String[] args) {
    try {
      throw new RuntimeException();
    } finally {
      // Using 'return' inside the finally block
      // will silence any thrown exception.
      return;
    }
  }
} ///:~
```



## 9.异常的限制

当覆盖方法的时候，只能抛出在基类方法的异常说明里列出的那些异常。

## 10. 构造器

构造器中发生异常时，不能使用finally清理那些已经产的文件或其他链接，因为异常发生时不知道还有没有创建成功，因此不能在finally中清理.

## 11.异常匹配

抛出异常的时候,异常处理系统会按照代码的书写顺序找出"最近"的处理程序.找到匹配的处理程序之后,它就认为异常将得到处理,然后不再继续查找.

查找的时候并不要求抛出的异常同处理程序声明的异常完全匹配.派生类的对象也可以匹配其基类的处理程序.

## 总结

应该在下列情况下使用异常：

1. 在恰当的级别处理问题。（在知道该如何处理的情况下才捕获异常）
2. 解决问题并且重新调用产生异常的方法。
3. 进行少许修补，然后绕过异常发生的地方继续执行。
4. 用别的数据进行计算，以代替方法预计会返回的值。
5. 把当前运行环境下能做完的事尽量做完，然后把相同的异常重抛到更高层。
6. 把当前运行环境下能做完的事情尽量做完，然后把不同的异常抛到更高层。
7. 终止程序。
8. 进行简化。
9. 让类库更安全。

异常处理的优点之一是它使得你可以在某处集中精力处理你要解决的问题，而在另一处处理你编写的这段代码中产生的问题。

